name: Build Miku-UI for Pacman

on:
  workflow_dispatch: # กดปุ่ม run เองจาก Actions tab

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 720 # เพิ่มเวลาสำหรับ build ใหญ่
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git aria2 ccache python3 openjdk-11-jdk \
          bc bison build-essential curl flex libncurses5-dev libssl-dev \
          unzip zip zlib1g-dev

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Prepare local manifest
        run: |
          mkdir -p $GITHUB_WORKSPACE/.repo/local_manifests
          cp $GITHUB_WORKSPACE/roomservice.xml $GITHUB_WORKSPACE/.repo/local_manifests/

      - name: Init repo
        run: |
          mkdir -p miku-ui
          cd miku-ui
          repo init -u https://github.com/Miku-UI/manifesto.git -b Blooming
          cp $GITHUB_WORKSPACE/.repo/local_manifests/roomservice.xml .repo/local_manifests/

      - name: Sync source
        run: |
          cd miku-ui
          repo sync -c --force-sync --no-clone-bundle --no-tags -j4

      - name: Setup build environment
        run: |
          cd miku-ui
          source build/envsetup.sh

      - name: Lunch target
        run: |
          cd miku-ui
          lunch lineage_Pacman-userdebug

      - name: Build ROM
        run: |
          cd miku-ui
          make bacon -j$(nproc --all)

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: Miku-UI-Pacman
          path: miku-ui/out/target/product/*/*.zip
